# Generated by Django 2.1.7 on 2019-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='yeargroup',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'BS'), (1, 'MS')], verbose_name='type of group'),
        ),
    ]
