# Generated by Django 2.1.7 on 2019-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190330_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Site Administrator'), (1, 'Building Administrator'), (2, 'Teaching Staff'), (3, 'Student')], default=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
