# Generated by Django 2.1.7 on 2019-03-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("rooms", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="item",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.Room",
            ),
        )
    ]
