# Generated by Django 2.1.7 on 2019-03-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_item_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rooms.Room'),
        ),
    ]
