# Generated by Django 2.1.7 on 2019-03-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20190317_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.ItemType'),
            preserve_default=False,
        ),
    ]
