image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker info
  - apk add --no-cache py-pip
  - pip install docker-compose --no-cache-dir

docker-build:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest -f docker/app/Dockerfile .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest

test:
  stage: test
  script:
    - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    - docker-compose -f docker-compose.autotest.yml run python
  after_script:
    - docker-compose -f docker-compose.autotest.yml down -v

deploy-prod:
  stage: deploy
  script:
    - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    - docker-compose -f docker-compose.yml  stop
    - docker-compose -f docker-compose.yml  rm -f
    - docker-compose -f docker-compose.yml  up -d
  tags:
    - docker
    - gobotat
