version: '3'
services:
  python:
    image: registry.gitlab.com/automatic-timetable-creation/backend:${CI_COMMIT_REF_SLUG}_python
    command: /bin/bash -c "pip install -r ./requirements_test.txt &&
              pytest --cov='.' --cov-config .coveragerc --ds atc.settings_test &&
              python3 manage.py test --settings=atc.settings_test"
  postgres:
      restart: always
      image: postgres:11.2-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      networks:
        - project

networks:
  project:
