version: '3'
services:
  python:
    image: registry.gitlab.com/automatic-timetable-creation/backend:latest
    ports:
      - 80:80
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always
    networks:
      - project

  postgres:
    restart: always
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - project

volumes:
 db_data:

networks:
  project:

