version: '3'
services:
  python:
    image: registry.gitlab.com/automatic-timetable-creation/backend:latest
    command: /bin/bash -c "pip install -r ./requirements_test.txt &&
              pytest --cov=atc ./schedule/tests.py &&
              python3 manage.py test --settings=atc.settings_test"
    restart: always
    networks:
      - project

networks:
  project:

