version: '3'
services:
  python:
    image: registry.gitlab.com/automatic-timetable-creation/backend:latest
    ports:
      - 80:80

  postgres:
    restart: always
    image: postgres:11.2-alpine
    ports:
      - 31337:5432
    volumes:
      - ./postgres/dump_init.sql:/docker-entrypoint-initdb.d/postgres_backup_all.sql

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
      PGDATA: /var/lib/postgresql/data/pgdata
 
