# Generated by Django 2.1.7 on 2019-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='semester',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Fall'), (0, 'Spring'), (1, 'Summer')], verbose_name='type of semester'),
        ),
    ]
