# Generated by Django 2.1.7 on 2019-03-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='class_id',
            new_name='current_class',
        ),
    ]
