# Generated by Django 2.2 on 2019-04-12 19:47

import django.core.validators
from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190325_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], validators=[django.core.validators.MaxValueValidator(7), rest_framework.compat.MinValueValidator(0)])),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(check=models.Q(day_of_week__gte=0), name='day_of_week_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(check=models.Q(day_of_week__lte=7), name='day_of_week_lte_7'),
        ),
    ]
