# Generated by Django 2.2 on 2019-04-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190412_1851'),
        ('schedule', '0003_auto_20190412_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='timeslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.Timeslot'),
            preserve_default=False,
        ),
    ]
