# Generated by Django 2.2 on 2019-04-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190412_1851'),
        ('schedule', '0004_auto_20190414_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ManyToManyField(related_name='events', to='users.Group'),
        ),
    ]
