# Generated by Django 2.2 on 2019-04-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190412_1851'),
        ('schedule', '0004_auto_20190414_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ManyToManyField(to='users.Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule.Timeslot'),
        ),
    ]
