# Generated by Django 2.2 on 2019-05-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190415_2317'),
        ('schedule', '0005_auto_20190430_1705'),
    ]

    operations = [
    ]
